### ISSUE TITLE
Missing tmp files blocking file manager

### ISSUE THREAD

**Issue by zhechenzhu** [Arksine/moonraker#185]
Hi, I'm using a stack of SuperSlicer to OctoPrint with OctoKlipper and a display with KlipperScreen. So far everything works expect job status showing on the KlipperScreen. Nothing shows up when a print job is uploaded. However the Gcode is visible from KlipperScreen's print menu and can be executed there with job status showing. 

As I was going through the moonraker log file, I found some errors related to parsing metadata at the same time when the Gcode is uploaded. It's trying to access some random tmpxxxx files which don't exist.

`2021-06-23 00:24:14,415 [file_manager.py:parse_gcode_metadata()] - Error retreiving path info for file /home/pi/gcode_files/tmpx4buxtet
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/file_manager.py", line 1125, in parse_gcode_metadata
    path_info = self.file_manager.get_path_info(file_path)
  File "/home/pi/moonraker/moonraker/components/file_manager.py", line 408, in get_path_info
    modified = os.path.getmtime(path)
  File "/home/pi/moonraker-env/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/gcode_files/tmpx4buxtet'
2021-06-23 00:24:14,425 [websockets.py:build_error()] - JSON-RPC Request Error: 404
Metadata not available for <tmpx4buxtet>
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 219, in execute_method
    result = await method(ws, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 312, in func
    ip_addr=ws.ip_addr, user=ws.current_user))
  File "/home/pi/moonraker/moonraker/components/file_manager.py", line 221, in _handle_metadata_request
    f"Metadata not available for <{requested_file}>", 404)
utils.ServerError: Metadata not available for <tmpx4buxtet>`

Any thought on how to resolve this? Who is responsible for generating these tmp files？

**Comment by zhechenzhu** [comment]
Sorry didn't configure my slicer properly. Works fine now. Closing.
