### ISSUE TITLE
Moonraker Warning - Supplied path for gcodes

### ISSUE THREAD

**Issue by midhunmonachan** [Arksine/moonraker#397]
### What happened

I'm getting two warnings on my dashboard and they are the same.

It says 
```
Supplied path (/home/pi/sdcard) for (gcodes) is invalid. Make sure that the path exists and is not the file system root.
```

I'm not sure where its getting that path from. In my cfg file I have 
```
[virtual_sdcard]
path: ~/gcode_files
```

I couldn't find anything about this error anywhere. But I'm able to upload gcode files from mainsailos file manager and they end up in `~/gcode_files` in my pi

Here is the log:

```
--------------------Moonraker Log Start--------------------
config_file: /home/pi/klipper_config/moonraker.conf
log_file: /home/pi/klipper_logs/moonraker.log
software_version: v0.7.1-453-gee312ee
python_version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
enable_debug_logging = False
max_upload_size = 1024

[file_manager]
config_path = ~/klipper_config
log_path = ~/klipper_logs
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[update_manager]
refresh_interval = 168

[update_manager mainsail]
type = web
repo = mainsail-crew/mainsail
path = ~/mainsail

#################################################################
Unsafe Shutdown Count: 7

System Info:

***python***
  version: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
  version_string: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: armv7l
  cpu_desc: ARMv7 Processor rev 3 (v7l)
  serial_number: 1000000052478e8f
  hardware_desc: BCM2711
  model: Raspberry Pi 4 Model B Rev 1.4
  total_memory: 7905608
  memory_units: kB

***sd_info***
  manufacturer_id: 09
  manufacturer: Unknown
  oem_id: 4150
  product_name: MC33A
  product_revision: 0.7
  serial_number: e3001b22
  manufacturer_date: 12/2019
  capacity: 29.0 GiB
  total_bytes: 31104958464

***distribution***
  name: Raspbian GNU/Linux 10 (buster)
  id: raspbian
  version: 10
  version_parts: {'major': '10', 'minor': '', 'build_number': ''}
  like: debian
  codename: buster
  release_info: {'name': 'MainsailOS', 'version_id': '0.6.1', 'codename': 'buster', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none
2022-03-14 22:57:22,848 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.198
2022-03-14 22:57:22,849 [app.py:log_request()] - 101 GET /websocket (192.168.0.198) [_TRUSTED_USER_] 3.78ms
2022-03-14 22:57:22,850 [websockets.py:open()] - Websocket Opened: ID: 2814052016, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0, Host Name: 192.168.0.21
2022-03-14 22:59:13,087 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 17.56ms
2022-03-14 22:59:14,168 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 22:59:14,171 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 22:59:15,428 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 22:59:15,681 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 22:59:15,683 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 22:59:17,443 [moonraker.py:add_warning()] - Supplied path (/home/pi/sdcard) for (gcodes) is invalid. Make sure
that the path exists and is not the file system root.
2022-03-14 22:59:17,458 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 22:59:17,949 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:03:00,965 [websockets.py:on_close()] - Websocket Closed: ID: 2814052016 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 8.11
2022-03-14 23:03:01,289 [app.py:log_request()] - 101 GET /websocket (192.168.0.198) [_TRUSTED_USER_] 4.76ms
2022-03-14 23:03:01,289 [websockets.py:open()] - Websocket Opened: ID: 2814142736, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0, Host Name: 192.168.0.21
2022-03-14 23:05:35,589 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 14.78ms
2022-03-14 23:05:36,663 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:05:36,667 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:05:37,927 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:05:38,181 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:05:38,183 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:05:39,689 [klippy_connection.py:_verify_klippy_requirements()] - 
Warning, unable to detect the following printer objects:
[virtual_sdcard]
Please add the the above sections to printer.cfg for full Moonraker functionality.
2022-03-14 23:05:39,703 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:05:40,199 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:06:48,966 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 13.96ms
2022-03-14 23:06:50,041 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:06:50,043 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:06:51,307 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:06:51,560 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:06:51,562 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:06:53,068 [klippy_connection.py:_verify_klippy_requirements()] - 
Warning, unable to detect the following printer objects:
[virtual_sdcard]
Please add the the above sections to printer.cfg for full Moonraker functionality.
2022-03-14 23:06:53,082 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:06:53,577 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:07:03,110 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:07:03,113 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:07:04,370 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:07:04,623 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:07:04,625 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:07:06,132 [klippy_connection.py:_verify_klippy_requirements()] - 
Warning, unable to detect the following printer objects:
[virtual_sdcard]
Please add the the above sections to printer.cfg for full Moonraker functionality.
2022-03-14 23:07:06,144 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:07:06,642 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:07:32,163 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 14.45ms
2022-03-14 23:07:33,233 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:07:33,238 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:07:43,821 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:07:43,944 [websockets.py:on_close()] - Websocket Closed: ID: 2814142736 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 2.65
2022-03-14 23:07:44,073 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:07:44,075 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:07:44,216 [app.py:log_request()] - 101 GET /websocket (192.168.0.198) [_TRUSTED_USER_] 2.43ms
2022-03-14 23:07:44,217 [websockets.py:open()] - Websocket Opened: ID: 2814171856, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0, Host Name: 192.168.0.21
2022-03-14 23:07:46,110 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:07:46,592 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:08:26,327 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 12.79ms
2022-03-14 23:08:27,403 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:08:27,405 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:08:28,663 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:08:28,916 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:08:28,918 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:08:30,716 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:08:31,207 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:12:20,258 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 23.40ms
2022-03-14 23:12:56,597 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 14.73ms
2022-03-14 23:12:57,672 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:12:57,675 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:12:58,937 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:12:59,190 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:12:59,192 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:13:00,992 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:13:01,483 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2022-03-14 23:16:22,986 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.198) [_TRUSTED_USER_] 15.29ms
2022-03-14 23:16:24,057 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-14 23:16:24,062 [websockets.py:build_error()] - JSON-RPC Request Error: 503
Klippy Disconnected
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 321, in func
    user=ws.current_user))
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 423, in request
    return await self._request_standard(web_request)
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 478, in _request_standard
    return await base_request.wait()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 548, in wait
    raise self.response
utils.ServerError: Klippy Disconnected
2022-03-14 23:16:25,319 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-14 23:16:25,572 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-14 23:16:25,573 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-14 23:16:27,389 [klippy_connection.py:_check_ready()] - Klippy ready
2022-03-14 23:16:27,879 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
```

### Client

Mainsail

### Browser

Firefox

### How to reproduce

Not really sure. It was there since the beginning of my install

**Comment by Arksine** [comment]
At some point you configured klipper's `[virtual_sdcard]` to use the path `/home/pi/sdcard`.  The warning was generated because the path does not exist.  You reconfigured to `/home/pi/gcode_files` which got it working.  To clear the warning you simply need to restart Moonraker.

**Comment by Arksine** [comment]
As this discussion seems to have concluded I am going to close this.

**Comment by Brick935** [comment]
I ran into the same issue lately, and I am unsure on how to restart Moonraker. It's probably a dumb question but I am I still struggling. Any help would be greatly appreciated
