### ISSUE TITLE
non stop disconnects

### ISSUE THREAD

**Issue by Fuckingnameless** [Arksine/moonraker#454]
### What happened

since updating a couple days ago it disconnects frenetically, i will attach the corresponding part of the log below

### Client

Mainsail

### Browser

Brave

### How to reproduce

do nothing

### Additional information

2022-07-04 14:23:04,224 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/login
2022-07-04 14:23:04,225 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/logout
2022-07-04 14:23:04,227 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/refresh_jwt
2022-07-04 14:23:04,229 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST DELETE) /access/user
2022-07-04 14:23:04,237 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /access/users/list
2022-07-04 14:23:04,238 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/user/password
2022-07-04 14:23:04,240 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST) /access/api_key
2022-07-04 14:23:04,247 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /access/oneshot_token
2022-07-04 14:23:04,249 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /access/info
2022-07-04 14:23:04,250 [moonraker.py:load_component()] - Component (authorization) loaded
2022-07-04 14:23:04,259 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/version
2022-07-04 14:23:04,260 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/server
2022-07-04 14:23:04,263 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/login
2022-07-04 14:23:04,267 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/currentuser
2022-07-04 14:23:04,268 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/settings
2022-07-04 14:23:04,272 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/job
2022-07-04 14:23:04,279 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/printer
2022-07-04 14:23:04,280 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/printer/command
2022-07-04 14:23:04,282 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/printerprofiles
2022-07-04 14:23:04,284 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/files/moonraker/(?P<relative_path>.+)
2022-07-04 14:23:04,294 [moonraker.py:load_component()] - Component (octoprint_compat) loaded
2022-07-04 14:23:04,300 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET DELETE) /server/history/job
2022-07-04 14:23:04,301 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.get_job, server.history.delete_job
2022-07-04 14:23:04,301 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/history/list
2022-07-04 14:23:04,302 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.list
2022-07-04 14:23:04,303 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/history/totals
2022-07-04 14:23:04,304 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.totals
2022-07-04 14:23:04,304 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/history/reset_totals
2022-07-04 14:23:04,316 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.reset_totals
2022-07-04 14:23:04,326 [moonraker.py:load_component()] - Component (history) loaded
2022-07-04 14:23:04,445 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/moonraker
2022-07-04 14:23:04,447 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.moonraker
2022-07-04 14:23:04,447 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/klipper
2022-07-04 14:23:04,448 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.klipper
2022-07-04 14:23:04,449 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/system
2022-07-04 14:23:04,450 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.system
2022-07-04 14:23:04,450 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/client
2022-07-04 14:23:04,456 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.client
2022-07-04 14:23:04,457 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/full
2022-07-04 14:23:04,458 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.full
2022-07-04 14:23:04,458 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /machine/update/status
2022-07-04 14:23:04,459 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.status
2022-07-04 14:23:04,459 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/recover
2022-07-04 14:23:04,460 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.recover
2022-07-04 14:23:04,461 [moonraker.py:load_component()] - Component (update_manager) loaded
2022-07-04 14:23:04,492 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/timelapse/render
2022-07-04 14:23:04,494 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.timelapse.render
2022-07-04 14:23:04,494 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/timelapse/saveframes
2022-07-04 14:23:04,506 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.timelapse.saveframes
2022-07-04 14:23:04,507 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST) /machine/timelapse/settings
2022-07-04 14:23:04,509 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.timelapse.get_settings, machine.timelapse.post_settings
2022-07-04 14:23:04,509 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /machine/timelapse/lastframeinfo
2022-07-04 14:23:04,511 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.timelapse.lastframeinfo
2022-07-04 14:23:04,515 [moonraker.py:load_component()] - Component (timelapse) loaded
2022-07-04 14:23:04,517 [moonraker.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2022-07-04 14:23:04,707 [moonraker.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2022-07-04 14:23:05,074 [moonraker.py:_initialize_component()] - Performing Component Post Init: [machine]
2022-07-04 14:23:05,951 [machine.py:check_virt_status()] - No Virtualization Detected
2022-07-04 14:23:05,975 [moonraker.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2022-07-04 14:23:05,976 [moonraker.py:_initialize_component()] - Performing Component Post Init: [announcements]
2022-07-04 14:23:05,981 [moonraker.py:_initialize_component()] - Performing Component Post Init: [authorization]
2022-07-04 14:23:05,981 [moonraker.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2022-07-04 14:23:06,501 [update_manager.py:initialize()] - PackageDeploy: Using PackageKit Provider
2022-07-04 14:23:06,510 [update_manager.py:initialize()] - 
Initializing Client Updater: 'mainsail',
Channel: stable
path: /home/pi/mainsail
2022-07-04 14:23:06,520 [moonraker.py:start_server()] - Starting Moonraker on (0.0.0.0, 7126), Hostname: raspberrypi
2022-07-04 14:23:06,528 [app.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2022-07-04 14:23:06,782 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-07-04 14:23:08,191 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-07-04 14:23:08,230 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-07-04 14:23:08,234 [moonraker.py:add_log_rollover_item()] - Klipper Version: v0.10.0-508-g1636a975
2022-07-04 14:23:10,544 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/info
2022-07-04 14:23:10,546 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.info
2022-07-04 14:23:10,546 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/query_endstops/status
2022-07-04 14:23:10,547 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.query_endstops.status
2022-07-04 14:23:10,547 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/emergency_stop
2022-07-04 14:23:10,548 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.emergency_stop
2022-07-04 14:23:10,548 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/pause
2022-07-04 14:23:10,549 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.pause
2022-07-04 14:23:10,550 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/query
2022-07-04 14:23:10,557 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.query
2022-07-04 14:23:10,558 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/list
2022-07-04 14:23:10,559 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.list
2022-07-04 14:23:10,559 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/motion_report/dump_stepper
2022-07-04 14:23:10,562 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.motion_report.dump_stepper
2022-07-04 14:23:10,563 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/firmware_restart
2022-07-04 14:23:10,564 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.firmware_restart
2022-07-04 14:23:10,564 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/subscribe
2022-07-04 14:23:10,566 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.subscribe
2022-07-04 14:23:10,566 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/script
2022-07-04 14:23:10,567 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.script
2022-07-04 14:23:10,568 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/help
2022-07-04 14:23:10,571 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.help
2022-07-04 14:23:10,571 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/resume
2022-07-04 14:23:10,573 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.resume
2022-07-04 14:23:10,573 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/motion_report/dump_trapq
2022-07-04 14:23:10,576 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.motion_report.dump_trapq
2022-07-04 14:23:10,577 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/cancel
2022-07-04 14:23:10,580 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.cancel
2022-07-04 14:23:10,581 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/restart
2022-07-04 14:23:10,582 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.restart
2022-07-04 14:23:10,703 [job_state.py:_handle_started()] - Job state initialized: standby
2022-07-04 14:23:11,020 [klippy_connection.py:_check_ready()] - Klippy ready
2022-07-04 14:23:11,456 [data_store.py:_init_sensors()] - Configuring available sensors: ['temperature_sensor raspberry_pi', 'heater_bed', 'temperature_sensor mcu_temp', 'extruder']
2022-07-04 14:23:36,244 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2022-07-04 14:23:42,597 [app.py:log_request()] - 101 GET /websocket (127.0.0.1) [_TRUSTED_USER_] 3.88ms
2022-07-04 14:23:42,598 [websockets.py:open()] - Websocket Opened: ID: 1749747696, Proxied: False, User Agent: , Host Name: localhost
2022-07-04 14:23:42,604 [websockets.py:build_error()] - JSON-RPC Request Error: -32601
Method not found
2022-07-04 14:23:45,012 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.15.2
2022-07-04 14:23:45,017 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 7.72ms
2022-07-04 14:23:45,018 [websockets.py:open()] - Websocket Opened: ID: 1749658480, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:23:45,023 [websockets.py:_handle_identify()] - Websocket 1749658480 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:23:47,412 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.16ms
2022-07-04 14:23:47,413 [websockets.py:open()] - Websocket Opened: ID: 1749658256, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:23:49,035 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:23:49,432 [websockets.py:build_error()] - JSON-RPC Request Error: -32601
Metadata not available for <>
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 253, in execute_method
    result = await callback(params)
  File "/home/pi/moonraker/moonraker/websockets.py", line 364, in func
    ip_addr=ws.ip_addr, user=ws.current_user))
  File "/home/pi/moonraker/moonraker/components/file_manager/file_manager.py", line 312, in _handle_metadata_request
    f"Metadata not available for <{requested_file}>", 404)
utils.ServerError: Metadata not available for <>
2022-07-04 14:24:27,878 [shell_command.py:run_with_response()] - /home/pi/moonraker-env/bin/python: Object Processing is disabled

2022-07-04 14:24:27,879 [shell_command.py:_check_proc_success()] - Command (/home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/pi/gcode_files -f "SS_base.gcode" -u "/tmp/moonraker.upload-82.mru") successfully finished
2022-07-04 14:24:27,893 [app.py:log_request()] - 201 POST /server/files/upload (192.168.15.2) [_TRUSTED_USER_] 21673.15ms
2022-07-04 14:24:55,520 [websockets.py:on_close()] - Websocket Closed: ID: 1749658480 Close Code: None, Close Reason: None, Pong Time Elapsed: 9.53
2022-07-04 14:24:55,524 [websockets.py:_process_messages()] - Websocket closed while writing: 1749658480
2022-07-04 14:24:55,914 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 4.79ms
2022-07-04 14:24:55,914 [websockets.py:open()] - Websocket Opened: ID: 1749658480, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:24:55,920 [websockets.py:_handle_identify()] - Websocket 1749658480 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:24:59,516 [websockets.py:on_close()] - Websocket Closed: ID: 1749658480 Close Code: None, Close Reason: None, Pong Time Elapsed: 3.61
2022-07-04 14:24:59,535 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 10.37ms
2022-07-04 14:24:59,537 [websockets.py:open()] - Websocket Opened: ID: 1749758384, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:24:59,542 [websockets.py:_handle_identify()] - Websocket 1749758384 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:02,087 [websockets.py:on_close()] - Websocket Closed: ID: 1749658256 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.67
2022-07-04 14:25:02,108 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 8.17ms
2022-07-04 14:25:02,109 [websockets.py:open()] - Websocket Opened: ID: 1749840880, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:02,264 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:25:02,640 [websockets.py:build_error()] - JSON-RPC Request Error: -32601
Metadata not available for <>
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 253, in execute_method
    result = await callback(params)
  File "/home/pi/moonraker/moonraker/websockets.py", line 364, in func
    ip_addr=ws.ip_addr, user=ws.current_user))
  File "/home/pi/moonraker/moonraker/components/file_manager/file_manager.py", line 312, in _handle_metadata_request
    f"Metadata not available for <{requested_file}>", 404)
utils.ServerError: Metadata not available for <>
2022-07-04 14:25:07,700 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 7.06ms
2022-07-04 14:25:07,701 [websockets.py:open()] - Websocket Opened: ID: 1749843120, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:07,706 [websockets.py:_handle_identify()] - Websocket 1749843120 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:11,595 [websockets.py:on_close()] - Websocket Closed: ID: 1749758384 Close Code: None, Close Reason: None, Pong Time Elapsed: 12.07
2022-07-04 14:25:13,062 [websockets.py:on_close()] - Websocket Closed: ID: 1749843120 Close Code: None, Close Reason: None, Pong Time Elapsed: 5.37
2022-07-04 14:25:13,063 [websockets.py:_process_messages()] - Websocket closed while writing: 1749843120
2022-07-04 14:25:13,071 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.27ms
2022-07-04 14:25:13,072 [websockets.py:open()] - Websocket Opened: ID: 1750120976, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:13,075 [websockets.py:_handle_identify()] - Websocket 1750120976 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:15,031 [websockets.py:on_close()] - Websocket Closed: ID: 1749840880 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.92
2022-07-04 14:25:15,048 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 7.43ms
2022-07-04 14:25:15,049 [websockets.py:open()] - Websocket Opened: ID: 1749858288, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:15,584 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:25:18,019 [websockets.py:on_close()] - Websocket Closed: ID: 1750120976 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.95
2022-07-04 14:25:18,026 [websockets.py:_process_messages()] - Websocket closed while writing: 1750120976
2022-07-04 14:25:18,332 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 2.93ms
2022-07-04 14:25:18,332 [websockets.py:open()] - Websocket Opened: ID: 1750166768, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:18,347 [websockets.py:_handle_identify()] - Websocket 1750166768 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:19,138 [websockets.py:on_close()] - Websocket Closed: ID: 1749858288 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.09
2022-07-04 14:25:20,073 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 5.02ms
2022-07-04 14:25:20,074 [websockets.py:open()] - Websocket Opened: ID: 1750330352, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:20,265 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:25:27,390 [websockets.py:on_close()] - Websocket Closed: ID: 1750166768 Close Code: None, Close Reason: None, Pong Time Elapsed: 9.06
2022-07-04 14:25:27,705 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 5.47ms
2022-07-04 14:25:27,706 [websockets.py:open()] - Websocket Opened: ID: 1749810928, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:27,715 [websockets.py:_handle_identify()] - Websocket 1749810928 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:28,039 [websockets.py:on_close()] - Websocket Closed: ID: 1750330352 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.97
2022-07-04 14:25:28,356 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.08ms
2022-07-04 14:25:28,357 [websockets.py:open()] - Websocket Opened: ID: 1749999824, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:29,275 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:25:42,661 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.11ms
2022-07-04 14:25:42,662 [websockets.py:open()] - Websocket Opened: ID: 1749746992, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:42,678 [websockets.py:_handle_identify()] - Websocket 1749746992 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:25:46,156 [websockets.py:on_close()] - Websocket Closed: ID: 1749810928 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.58
2022-07-04 14:25:46,183 [websockets.py:_process_messages()] - Websocket closed while writing: 1749810928
2022-07-04 14:25:57,352 [websockets.py:on_close()] - Websocket Closed: ID: 1749746992 Close Code: None, Close Reason: None, Pong Time Elapsed: 14.69
2022-07-04 14:25:57,364 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 6.86ms
2022-07-04 14:25:57,365 [websockets.py:open()] - Websocket Opened: ID: 1749788432, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:25:57,377 [websockets.py:_handle_identify()] - Websocket 1749788432 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:26:11,602 [klippy_connection.py:wait()] - Request 'gcode/script' pending: 60.00 seconds
2022-07-04 14:26:12,690 [websockets.py:on_close()] - Websocket Closed: ID: 1749999824 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.33
2022-07-04 14:26:12,701 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.89ms
2022-07-04 14:26:12,702 [websockets.py:open()] - Websocket Opened: ID: 1749761264, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:26:13,053 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-07-04 14:26:13,896 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 3.74ms
2022-07-04 14:26:13,897 [websockets.py:open()] - Websocket Opened: ID: 1750330992, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:26:13,901 [websockets.py:_handle_identify()] - Websocket 1750330992 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:26:13,955 [websockets.py:on_close()] - Websocket Closed: ID: 1749788432 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.84
2022-07-04 14:26:16,535 [websockets.py:on_close()] - Websocket Closed: ID: 1750330992 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.64
2022-07-04 14:26:16,548 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 6.18ms
2022-07-04 14:26:16,549 [websockets.py:open()] - Websocket Opened: ID: 1749787312, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:26:16,554 [websockets.py:_handle_identify()] - Websocket 1749787312 Client Identified - Name: mainsail, Version: 2.2.1, Type: web
2022-07-04 14:26:19,660 [websockets.py:on_close()] - Websocket Closed: ID: 1749761264 Close Code: None, Close Reason: None, Pong Time Elapsed: 6.96
2022-07-04 14:26:19,673 [app.py:log_request()] - 101 GET /websocket (192.168.15.2) [_TRUSTED_USER_] 5.64ms
2022-07-04 14:26:19,674 [websockets.py:open()] - Websocket Opened: ID: 1750121968, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36, Host Name: 192.168.15.3
2022-07-04 14:26:19,783 [file_manager.py:get_file_list()] - Updating File List <config>...

**Comment by Arksine** [comment]
It is necessary to attach the full log for me to make a complete diagnosis, however based on the snippet it appears to be a local networking error.   Neither Moonraker nor Mainsail requesting the websocket disconnection, its just dropping.

**Comment by Fuckingnameless** [comment]
> It is necessary to attach the full log for me to make a complete diagnosis, however based on the snippet it appears to be a local networking error. Neither Moonraker nor Mainsail requesting the websocket disconnection, its just dropping.

eee was the culprit it seems

https://forums.raspberrypi.com/viewtopic.php?t=305820

**Comment by Arksine** [comment]
Thanks for the update.  If the issue is EEE on a Pi 3B+ then that suggests a regression may have  been introduced in the kernel driver.  I'll keep this info tucked away, I may look into an faq for troubleshooting connection issues.
