### ISSUE TITLE
GPIO Permssions Denied

### ISSUE THREAD

**Issue by S1L3NTANG3L** [Arksine/moonraker#515]
### What happened

Moonraker is unable to access the gpio pins on my Radxa zero or the BTT CB1.
Log Output:
2022-10-02 13:02:25,273 [gpio.py:_request_gpio()] - Unable to init gpiochip0:gpio6.  Make sure the gpio is not in use by another program or exported by sysfs.
Traceback (most recent call last):
  File "/home/biqu/moonraker/moonraker/components/gpio.py", line 84, in _request_gpio
    chip = self._get_gpio_chip(pin_params['chip_id'])
  File "/home/biqu/moonraker/moonraker/components/gpio.py", line 40, in _get_gpio_chip
    chip = self.gpiod.Chip(chip_name, self.gpiod.Chip.OPEN_BY_NAME)
PermissionError: [Errno 13] Permission denied
2022-10-02 13:02:25,273 [moonraker.py:add_warning()] - Failed to load power device [power light_strip_2 ]
Error parsing option (pin) from section [power light_strip_2 ]

### Client

Mainsail

### Browser

Firefox

### How to reproduce

1. Use the default CB1 or Radxa Zero images :
1.1. radxa-zero-ubuntu-focal-server-arm64-20220801-0346-mbr.img.xz
1.2. CB1_Debian11_bullseye_Klipper_kernel5.16_20220929.img
2. Install everything using KIUH
3. Add a power device to the moonraker config that uses any of the gpio pins.
4. should get an error.

### Additional information

[moonraker.log](https://github.com/Arksine/moonraker/files/9692635/moonraker.log)

**Comment by S1L3NTANG3L** [comment]
Here's the solution for the CB1 -> [💯 ](https://github.com/bigtreetech/CB1/issues/44#issuecomment-1264733456)
