### ISSUE TITLE
Update Manager failed to start

### ISSUE THREAD

**Issue by m0uh85** [Arksine/moonraker#559]
### What happened

`2022-11-29 20:51:25,308 [moonraker.py:load_component()] - Unable to load component: (update_manager)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 255, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/update_manager/__init__.py", line 15, in load_component
    return um.load_component(config)
  File "/home/pi/moonraker/moonraker/components/update_manager/update_manager.py", line 1346, in load_component
    return UpdateManager(config)
  File "/home/pi/moonraker/moonraker/components/update_manager/update_manager.py", line 94, in __init__
    self.updaters['klipper'] = kclass(kcfg, self.cmd_helper)
  File "/home/pi/moonraker/moonraker/components/update_manager/git_deploy.py", line 33, in __init__
    super().__init__(config, cmd_helper)
  File "/home/pi/moonraker/moonraker/components/update_manager/app_deploy.py", line 131, in __init__
    self._verify_path(config, 'requirements', self.python_reqs)
  File "/home/pi/moonraker/moonraker/components/update_manager/app_deploy.py", line 156, in _verify_path
    raise config.error(
confighelper.ConfigError: Invalid path for option `requirements` in section [klipper]: Path `/home/pi/klipper/scripts/klippy-requirements.txt` does not exist`

### Client

Mainsail, MoonCord

### Browser

Chrome

### How to reproduce

I don't know :(

**Comment by Arksine** [comment]
Hopefully you are no longer experiencing this issue and were able to find help on the discord and/or discourse.  That said, it appears that something was wrong with your klipper installation, as Moonraker cannot find a file that should be present in the repo.
