### ISSUE TITLE
Missing or invalid secrets file prevents moonraker service from loading

### ISSUE THREAD

**Issue by zanhecht** [Arksine/moonraker#613]
### What happened

When the moonraker.secrets file is missing, or a requested password is missing, instead of raising a config.error message, jinja2 throws an UndefinedError and the entire moonraker service will fail to load.

### Client

Other

### Browser

Other or N/A

### How to reproduce

1. Add a call to the secrets file (e.g. [machine] sudo_password = {secrets.sudo.password}) to moonraker.conf
2. Add a blank [secrets] section to moonraker.conf
3. Do not create a moonraker.secrets file
4. Attempt to start the moonraker service

### Additional information

```
--------------------Moonraker Log Start--------------------
data_path: /home/pi/printer_data
is_default_data_path: False
config_file: /home/pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
log_file: /home/pi/printer_data/logs/moonraker.log
software_version: v0.7.1-874-gbec9a66
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
2023-02-14 10:06:32,833 [loghelper.py:__init__()] - data_path: /home/pi/printer_data
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - is_default_data_path: False
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - config_file: /home/pi/printer_data/config/moonraker.conf
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - startup_warnings: []
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - verbose: False
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - debug: False
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - asyncio_debug: False
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - is_backup_config: False
2023-02-14 10:06:32,834 [loghelper.py:__init__()] - log_file: /home/pi/printer_data/logs/moonraker.log
2023-02-14 10:06:32,835 [loghelper.py:__init__()] - software_version: v0.7.1-874-gbec9a66
2023-02-14 10:06:32,835 [loghelper.py:__init__()] - python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
2023-02-14 10:06:32,849 [confighelper.py:read_file()] - Configuration File '/home/pi/printer_data/config/moonraker.conf' parsed, total size: 5229 B
2023-02-14 10:06:32,850 [moonraker.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[machine]
sudo_password = {secrets.sudo.password}

[secrets]

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager]
refresh_interval = 168
enable_auto_refresh = True

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/install.sh

[update_manager sonar]
type = git_repo
path = ~/sonar
origin = https://github.com/mainsail-crew/sonar.git
primary_branch = main
managed_services = sonar
install_script = tools/install.sh

[power printer]
type = tasmota
address = 192.168.1.201
password = 
output_id = 1
off_when_shutdown = False
on_when_job_queued = True
locked_while_printing = True
restart_klipper_when_powered = True
restart_delay = 5
bound_services = 

[power lights]
type = tasmota
address = 192.168.1.202

[update_manager KlipperScreen]
type = git_repo
path = ~/KlipperScreen
origin = https://github.com/jordanruthe/KlipperScreen.git
env = ~/.KlipperScreen-env/bin/python
requirements = scripts/KlipperScreen-requirements.txt
install_script = scripts/KlipperScreen-install.sh
managed_services = KlipperScreen

#################################################################
All Configuration Files:
/home/pi/printer_data/config/moonraker.conf
#################################################################
2023-02-14 10:06:32,883 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/logs/rollover
2023-02-14 10:06:32,884 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.logs.rollover
2023-02-14 10:06:32,884 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/info
2023-02-14 10:06:32,885 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.info
2023-02-14 10:06:32,885 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/config
2023-02-14 10:06:32,885 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.config
2023-02-14 10:06:32,886 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/restart
2023-02-14 10:06:32,886 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.restart
2023-02-14 10:06:32,974 [moonraker.py:load_component()] - Component (dbus_manager) loaded
2023-02-14 10:06:32,985 [moonraker.py:add_log_rollover_item()] - Unsafe Shutdown Count: 80
2023-02-14 10:06:32,998 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/database/list
2023-02-14 10:06:32,999 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.database.list
2023-02-14 10:06:32,999 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST DELETE) /server/database/item
2023-02-14 10:06:33,000 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.database.get_item, server.database.post_item, server.database.delete_item
2023-02-14 10:06:33,000 [moonraker.py:load_component()] - Component (database) loaded
2023-02-14 10:06:33,060 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/files/list
2023-02-14 10:06:33,062 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.list
2023-02-14 10:06:33,062 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/files/metadata
2023-02-14 10:06:33,063 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.metadata
2023-02-14 10:06:33,063 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/files/thumbnails
2023-02-14 10:06:33,064 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.thumbnails
2023-02-14 10:06:33,064 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/files/roots
2023-02-14 10:06:33,064 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.roots
2023-02-14 10:06:33,065 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST DELETE) /server/files/directory
2023-02-14 10:06:33,065 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.get_directory, server.files.post_directory, server.files.delete_directory
2023-02-14 10:06:33,066 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/files/move
2023-02-14 10:06:33,067 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.move
2023-02-14 10:06:33,067 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/files/copy
2023-02-14 10:06:33,068 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.copy
2023-02-14 10:06:33,068 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/files/zip
2023-02-14 10:06:33,068 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.zip
2023-02-14 10:06:33,069 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.files.delete_file
2023-02-14 10:06:33,080 [moonraker.py:load_component()] - Component (file_manager) loaded
2023-02-14 10:06:33,084 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/print/pause
2023-02-14 10:06:33,085 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.print.pause
2023-02-14 10:06:33,085 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/print/resume
2023-02-14 10:06:33,086 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.print.resume
2023-02-14 10:06:33,086 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/print/cancel
2023-02-14 10:06:33,087 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.print.cancel
2023-02-14 10:06:33,087 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/print/start
2023-02-14 10:06:33,087 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.print.start
2023-02-14 10:06:33,087 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/restart
2023-02-14 10:06:33,089 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.restart
2023-02-14 10:06:33,089 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /printer/firmware_restart
2023-02-14 10:06:33,090 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.firmware_restart
2023-02-14 10:06:33,090 [moonraker.py:load_component()] - Component (klippy_apis) loaded
2023-02-14 10:06:33,404 [moonraker.py:load_component()] - Component (secrets) loaded
2023-02-14 10:06:33,418 [moonraker.py:load_component()] - Component (template) loaded
2023-02-14 10:06:33,435 [moonraker.py:load_component()] - Unable to load component: (machine)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 255, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/machine.py", line 2006, in load_component
    return Machine(config)
  File "/home/pi/moonraker/moonraker/components/machine.py", line 102, in __init__
    self._sudo_password = sudo_template.render()
  File "/home/pi/moonraker/moonraker/components/template.py", line 92, in render
    return self.template.render(context).strip()
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'components.secrets.Secrets object' has no attribute 'sudo'
2023-02-14 10:06:33,435 [moonraker.py:main()] - Moonraker Error
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 255, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/machine.py", line 2006, in load_component
    return Machine(config)
  File "/home/pi/moonraker/moonraker/components/machine.py", line 102, in __init__
    self._sudo_password = sudo_template.render()
  File "/home/pi/moonraker/moonraker/components/template.py", line 92, in render
    return self.template.render(context).strip()
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'components.secrets.Secrets object' has no attribute 'sudo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 501, in main
    server.load_components()
  File "/home/pi/moonraker/moonraker/moonraker.py", line 231, in load_components
    self.load_component(config, component)
  File "/home/pi/moonraker/moonraker/moonraker.py", line 262, in load_component
    raise ServerError(msg)
utils.ServerError: Unable to load component: (machine)
2023-02-14 10:06:33,437 [moonraker.py:main()] - Server Shutdown
```

**Comment by Arksine** [comment]
Thanks, this should be resolved in 87dba2f2e2c78267b2ce9d4a4f54d4aa0bc7ed8a.

**Comment by JaysenSingh** [comment]
Hi all, can anyone help with this error please. I've updated moonraker via fluidd notification and then this error happened. ![image](https://github.com/Arksine/moonraker/assets/70598960/4881db35-858b-4307-9396-f99987c9ed03)

**Comment by Arksine** [comment]
You will need to provide `moonraker.log`.  The error suggests that you have a version of pylmdb installed that is very old, older than the version initially added with Moonraker.

**Comment by JaysenSingh** [comment]
Hi Eric,
Thank you for your reply, I have attached my log file for viewing.
Any help is greatly appreciated.
Thanks,Jay
    On Thursday, 28 December 2023 at 00:52:47 GMT, Eric Callahan ***@***.***> wrote:  
 
 


You will need to provide moonraker.log. The error suggests that you have a version of pylmdb installed that is very old, older than the version initially added with Moonraker.

**Comment by Arksine** [comment]
@JaysenSingh I don't believe that the log attached correctly.  That said, others are experiencing this issue, please follow #781.
