### ISSUE TITLE
Add Jeedom support for Power device

### ISSUE THREAD

**Issue by mikebzh44** [Arksine/moonraker#619]
### Is your feature request related to a problem? Please describe

No related to a problem

### Describe the solution you'd like

Hi.

My printer can be power On and Off from Jeedom by sending an URL.

So I tried to modify power.py by adding a new entry : 

`
class PrinterPower:
    def __init__(self, config: ConfigHelper) -> None:
        self.server = config.get_server()
        self.devices: Dict[str, PowerDevice] = {}
        prefix_sections = config.get_prefix_sections("power")
        logging.info(f"Power component loading devices: {prefix_sections}")
        dev_types = {
            "gpio": GpioDevice,
            "klipper_device": KlipperDevice,
            "tplink_smartplug": TPLinkSmartPlug,
            "tasmota": Tasmota,
            "shelly": Shelly,
            "homeseer": HomeSeer,
            "homeassistant": HomeAssistant,
            "loxonev1": Loxonev1,
            "rf": RFDevice,
            "mqtt": MQTTDevice,
            "smartthings": SmartThings,
            "hue": HueDevice,
            "jeedom": Jeedom
        }
`

And I add this block of code at the end : 

`
class Jeedom(HTTPDevice):
    def __init__(self, config: ConfigHelper) -> None:
        super().__init__(config)
        self.apikey: str = config.gettemplate("token").render()
        self.id_state: str = config.get("id_state")
        self.id_on: str = config.get("id_on")
        self.id_off: str = config.get("id_off")

    async def _send_jeedom_command(self, command: str) -> Dict[str, Any]:
        query_args: Dict[str, Any] = {}
        if command == "on":
            id_cmd = self.id_on
        elif command == "off":
            id_cmd = self.id_off
        elif command == "info":
            id_cmd = self.id_state
        elif command != "info":
            raise self.server.error(f"Invalid jeedom command: {command}")
        url = f"{self.protocol}://{quote(self.addr)}:{self.port}/core/api/jeeApi.php?apikey={self.apikey}&type=cmd&id={id_cmd}"
        return await self._send_http_command(url, command)

    async def _send_status_request(self) -> str:
        res = await self._send_jeedom_command("info")
        state: str = res[f"ison"]
        timer_remaining = res[f"timer_remaining"] if self.timer != "" else 0
        return "on" if state and timer_remaining == 0 else "off"

    async def _send_power_request(self, state: str) -> str:
        res = await self._send_jeedom_command(state)
        state = res[f"ison"]
        timer_remaining = res[f"timer_remaining"] if self.timer != "" else 0
        return "on" if state and timer_remaining == 0 else "off"
`

For now, my code is not clean, I don't deal with return code, I just mant to see if URL is send to Jeedom.

In moonraker.conf, I added this code : 

`
[power jeedom_switch]
type: jeedom
protocol: http
address: 192.168.0.192
port: 80
apikey: QQc1lFIiCVBZCZDwOiAGaMswaORgcpFpHKUBXK9xl7syhlHN
id_state: 995
id_on: 993
id_off: 994`

I have to define 3 IDs because in Jeedom, each command (On, Off, State, ...) is attached to it's own URL.

But when I restart moonraker, this errors are raised in the log file : 

`
2023-02-21 22:50:57,919 [moonraker.py:load_component()] - Unable to load component: (power)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 261, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/power.py", line 1405, in load_component
  File "/home/pi/moonraker/moonraker/components/power.py", line 67, in __init__
confighelper.ConfigError: Unsupported Device Type: jeedom
`

I based my code on Shelly device and I've looked into all Python files in moonraker and the only fil refering to shelly is power.py so where is my mistake ?

Thanks for your help.

**Comment by mikebzh44** [comment]
No help :( ?
