### ISSUE TITLE
Problem with SimplyPrint Plugin at version v0.8.0-4-g80fb97c

### ISSUE THREAD

**Issue by jerrythecok** [Arksine/moonraker#623]
### What happened

I updated my Klipper instance for one Printer to Version v0.8.0-4-g80fb97c
and i got an error from the Simplyprint Plugin Python Plugin

"
/simplyprint.py", line 22, in <module>
    from loghelper import LocalQueueHandler
ModuleNotFoundError: No module named 'loghelper'
"

### Client

Fluidd

### Browser

Chrome

### How to reproduce

upgrade to version v0.8.0-4-g80fb97c use simplyprint plugin

### Additional information

Logs:

2023-02-24 11:08:46,336 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/extensions/request
2023-02-24 11:08:46,337 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.extensions.request
2023-02-24 11:08:46,337 [server.py:load_component()] - Component (extensions) loaded
2023-02-24 11:08:46,377 [server.py:load_component()] - Unable to load component: (simplyprint)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/server.py", line 265, in load_component
    module = importlib.import_module(full_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/moonraker/moonraker/components/simplyprint.py", line 22, in <module>
    from loghelper import LocalQueueHandler
ModuleNotFoundError: No module named 'loghelper'
2023-02-24 11:08:46,472 [base_deploy.py:log_info()] - Application moonraker: Detected virtualenv: /home/pi/moonraker-env
2023-02-24 11:08:46,474 [base_deploy.py:log_info()] - Application klipper: Detected virtualenv: /home/pi/klippy-env
2023-02-24 11:08:46,476 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/moonraker
2023-02-24 11:08:46,477 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.moonraker
2023-02-24 11:08:46,477 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/klipper
2023-02-24 11:08:46,477 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.klipper
2023-02-24 11:08:46,477 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/system
2023-02-24 11:08:46,477 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.system
2023-02-24 11:08:46,477 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/client
2023-02-24 11:08:46,478 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.client

**Comment by Arksine** [comment]
Thanks.  This should be fixed in commit 160f6d64be4ee9488fb123cbe56569b47fcda31c.
