### ISSUE TITLE
Fluidd can't connect to Moonraker (CORS ?)

### ISSUE THREAD

**Issue by SaturninPL** [Arksine/moonraker#645]
### What happened

I've upgraded moonraker to version 0.8.0-35 and Fluidd can't connect to it: "No moonraker connection. Please check moonraker status and / or refresh.".
I've reinstalled Moonraker from GIT source.
I guess that there is something wrong with CORS (KlipperScreen on LCD works).
Can I ask for an assistance?

Moonraker summary page (Windows IP 192.168.0.42, Moonraker IP 192.168.0.60:7125):
Authorization
Request IP:192.168.0.42 Authorized:True CORS Enabled:False
Summary
The [authorization] component is not enabled in moonraker.conf. All connections will be considered trusted.
All cross origin requests will be blocked by the browser. The [authorization] section in moonraker.conf must be configured to enable CORS.
Klipper reports printer is ready
Warnings
Unparsed config section [authorization] detected. This may be the result of a component that failed to load. In the future this will result in a startup error.

Manual access to /access/oneshot_token from Windows 192.168.0.42 (http://192.168.0.60:7125/access/oneshot_token):
{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/mks/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 1690, in _execute\n    result = self.prepare()\n\n  File \"/home/mks/moonraker/moonraker/app.py\", line 962, in prepare\n    raise tornado.web.HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}

### Client

Fluidd

### Browser

Chrome

### How to reproduce

Upgrade Moonraker, try to connect to it via web interface (Fluidd).

### Additional information

[moonraker.log](https://github.com/Arksine/moonraker/files/11271270/moonraker.log)
[moonraker.conf.txt](https://github.com/Arksine/moonraker/files/11271278/moonraker.conf.txt)

**Comment by SaturninPL** [comment]
Great idea ! You will find extended log in attachment (I've removed log of previous restarts from the start of the file).
[moonraker.log](https://github.com/Arksine/moonraker/files/11297999/moonraker.log)

Most likely culprit is here:
2023-04-21 19:18:07,346 [server.py:load_component()] - Component (history) loaded
2023-04-21 19:18:07,366 [server.py:load_component()] - Unable to load component: (authorization)
Traceback (most recent call last):
  File "/home/mks/moonraker/moonraker/server.py", line 266, in load_component
    module = importlib.import_module(full_name)
  File "/home/mks/moonraker-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mks/moonraker/moonraker/components/authorization.py", line 22, in <module>
    from libnacl.sign import Signer, Verifier
ImportError: cannot import name 'Signer' from 'libnacl.sign' (/home/mks/moonraker-env/lib/python3.7/site-packages/libnacl/sign.py)

My moonraker-env seems to be messed up (size 0):
mks@mkspi:~/moonraker-env/lib/python3.7/site-packages$ ls -la libnacl*
libnacl:
total 12
drwxr-xr-x   3 mks mks 4096 Apr 13 21:45 .
drwxr-xr-x 131 mks mks 4096 Apr 18 22:14 ..
-rw-r--r--   1 mks mks    0 Apr 13 21:45 aead.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 base.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 blake.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 dual.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 encode.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 __init__.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 public.py
drwxr-xr-x   2 mks mks 4096 Apr 18 22:13 __pycache__
-rw-r--r--   1 mks mks    0 Apr 13 21:45 sealed.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 secret_easy.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 secret.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 sign.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 utils.py
-rw-r--r--   1 mks mks    0 Apr 13 21:45 version.py

**Comment by SaturninPL** [comment]
I've removed moonraker-env directory, reinstalled whole moonraker and it helped.

Thank You for pointing me in a right direction !
