### ISSUE TITLE
Make unix socket path configurable

### ISSUE THREAD

**Issue by mapero** [Arksine/moonraker#689]
### Is your feature request related to a problem? Please describe

Hi,

thanks for implementing moonraker.

I am currently working on a snap integration to make this run together with klippy in an ubuntu core environment.
However I stumpled over an issue with regard to the unix socket that moonraker is creating in the data directory.

Since the path length for unix socket in linux is limited to 108 chars, and the snap environment is very strict where you can store things. I run into this issue.

```
2023-07-21T18:41:14Z klipper.moonraker[34089]: [eventloop.py:_wrapper()] - Error Running Callback
2023-07-21T18:41:14Z klipper.moonraker[34089]: Traceback (most recent call last):
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/snap/klipper/x19/moonraker/eventloop.py", line 73, in _wrapper
2023-07-21T18:41:14Z klipper.moonraker[34089]:     await ret
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/snap/klipper/x19/moonraker/server.py", line 183, in server_init
2023-07-21T18:41:14Z klipper.moonraker[34089]:     await self.start_server()
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/snap/klipper/x19/moonraker/server.py", line 188, in start_server
2023-07-21T18:41:14Z klipper.moonraker[34089]:     await extm.start_unix_server()
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/snap/klipper/x19/moonraker/components/extensions.py", line 122, in start_unix_server
2023-07-21T18:41:14Z klipper.moonraker[34089]:     self.uds_server = await asyncio.start_unix_server(
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/usr/lib/python3.10/asyncio/streams.py", line 113, in start_unix_server
2023-07-21T18:41:14Z klipper.moonraker[34089]:     return await loop.create_unix_server(factory, path, **kwds)
2023-07-21T18:41:14Z klipper.moonraker[34089]:   File "/usr/lib/python3.10/asyncio/unix_events.py", line 306, in create_unix_server
2023-07-21T18:41:14Z klipper.moonraker[34089]:     sock.bind(path)
2023-07-21T18:41:14Z klipper.moonraker[34089]: OSError: AF_UNIX path too long
```

If the unix port of moonraker could be configurable e.g. as part of the configuration file or/and as commandline argument, it would be possible to set it to /tmp/moonraker.sock or similar.

I guess this is where the magic happens
https://github.com/Arksine/moonraker/blob/26975e055b6e3f3d5b46f7f73911738901355713/moonraker/components/extensions.py#L120

### Describe the solution you'd like

If the unix port of moonraker could be configurable e.g. as part of the configuration file or/and as commandline argument, it would be possible to set it to /tmp/moonraker.sock or similar.

**Comment by Arksine** [comment]
Commit 1fadae885ed1eb8c2447249d1c03a218db42c0c8 should resolve this.
