### ISSUE TITLE
Shelly power device - special character `*` in password is not working

### ISSUE THREAD

**Issue by MoJo2600** [Arksine/moonraker#701]
### What happened

My printer is connected to a shelly 1 to power up the printer from the GUI. It was working, but after an update (I don't know the version) the device stopped working. I investigated the issue in version v0.8.0-136 and the logs show an error `401 Unauthorized` when initializing the shelly device. I tried moving the password to a `moonraker.secrets` file. But the result was the same. Only after I removed the special character `*` from the password and the password only containing characters and numbers, the device started working again. I did not try other special characters or other devices. I believe the issue is with the jinja templating of the password string.

### Client

Mainsail

### Browser

Chrome

### How to reproduce

Set the password of a shelly device to e.g. `AbCdEfG*123HiJ` the device will not work and the error in the logs show `401 Unauthorized`

### Additional information

```
-------------------- Log Start | Mon Aug 14 10:46:51 2023 --------------------
data_path: /home/klipper/printer_data
is_default_data_path: False
config_file: /home/klipper/klipper_config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: 28fee33943d4485fa2c4886c763423dd
unix_socket_path: /home/klipper/printer_data/comms/moonraker.sock
software_version: v0.8.0-136-g797c623
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/klipper/klipper_logs/moonraker.log
python_version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /tmp/klippy_uds

[database]

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[file_manager]

[octoprint_compat]

[history]

[update_manager]
channel = dev

[update_manager mainsail]
type = web
repo = mainsail-crew/mainsail
path = ~/mainsail
refresh_interval = 24

[update_manager fluidd]
type = web
repo = fluidd-core/fluidd
path = ~/fluidd
refresh_interval = 24

[power printer]
type = shelly
address = 192.168.158.20
user = admin
password = pWFdJd5h*CvtuNFgksTSm

[update_manager timelapse]
type = git_repo
primary_branch = main
path = ~/moonraker-timelapse
origin = https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services = klipper moonraker

[update_manager KlipperScreen]
type = git_repo
path = ~/KlipperScreen
origin = https://github.com/jordanruthe/KlipperScreen.git
env = ~/.KlipperScreen-env/bin/python
requirements = scripts/KlipperScreen-requirements.txt
install_script = scripts/KlipperScreen-install.sh
managed_services = KlipperScreen

[timelapse]
output_path = ~/timelapse/
frame_path = /tmp/timelapse/
ffmpeg_binary_path = /usr/bin/ffmpeg

#################################################################
All Configuration Files:
/home/klipper/klipper_config/moonraker.conf
#################################################################
Unsafe Shutdown Count: 2

System Info:

***python***
  version: sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
  version_string: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: armv7l
  cpu_desc: ARMv7 Processor rev 4 (v7l)
  serial_number: f4feb6ec
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Rev 1.2
  total_memory: 944092
  memory_units: kB

***sd_info***
  manufacturer_id: 1b
  manufacturer: Samsung
  oem_id: 534d
  product_name: EC2QT
  product_revision: 3.0
  serial_number: fa025f3c
  manufacturer_date: 7/2017
  capacity: 59.6 GiB
  total_bytes: 64021856256

***distribution***
  name: Raspbian GNU/Linux 11 (bullseye)
  id: raspbian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: debian
  codename: bullseye
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'network-online.target', '-.mount', 'system.slice']
**After=['sysinit.target', 'network-online.target', 'systemd-journald.socket', 'basic.target', '-.mount', 'system.slice']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/klipper/printer_data/systemd/moonraker.env
**ExecStart=/home/klipper/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/klipper/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=klipper

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice']
**After=['network.target', 'basic.target', 'system.slice', 'systemd-journald.socket', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=[]
**ExecStart=/home/klipper/klippy-env/bin/python /home/klipper/klipper/klippy/klippy.py /home/klipper/klipper_config/printer.cfg -I /tmp/printer -l /home/klipper/klipper_logs/klippy.log -a /tmp/klippy_uds
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Starts klipper instance  on startup
**User=klipper
CPU Throttled Flags: ['Under-Voltage Detected', 'Currently Throttled', 'Previously Under-Volted', 'Previously Throttled']
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
Git Repo klipper: No warnings detected
2023-08-14 12:46:49,506 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/klipper/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: 797c62389d31de2ec6c386af83b9cd0957f50068
Upstream Commit SHA: fe120952ee06607d039af8f461028e9f5b817395
Current Version: v0.8.0-136-g797c6238
Upstream Version: v0.8.0-138-gfe120952
Rollback Commit: 797c62389d31de2ec6c386af83b9cd0957f50068
Rollback Branch: master
Rollback Version: v0.8.0-136-g797c623
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 2
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2023-08-14 12:46:50,073 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/klipper/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: ed66982b8eb06ce8843d8b5163c6bd290e1754c9
Upstream Commit SHA: aa8ba30f8a8453c739a009870752fb645ed4c27b
Current Version: v0.11.0-257-ged66982b
Upstream Version: v0.11.0-261-gaa8ba30f
Rollback Commit: ed66982b8eb06ce8843d8b5163c6bd290e1754c9
Rollback Branch: master
Rollback Version: v0.11.0-257-ged66982b
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 4
Diverged: False
2023-08-14 12:46:51,200 [power.py:init_state()] - Device Init Error: printer
tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker/moonraker/components/power.py", line 446, in init_state
    state = await self._send_status_request()
  File "/home/klipper/moonraker/moonraker/components/power.py", line 1012, in _send_status_request
    res = await self._send_shelly_command("info")
  File "/home/klipper/moonraker/moonraker/components/power.py", line 1009, in _send_shelly_command
    return await self._send_http_command(url, command)
  File "/home/klipper/moonraker/moonraker/components/power.py", line 478, in _send_http_command
    response.raise_for_status(
  File "/home/klipper/moonraker/moonraker/components/http_client.py", line 363, in raise_for_status
    raise ServerError(msg, code) from self._error
moonraker.utils.ServerError: Error sending 'shelly' command: info
2023-08-14 12:46:52,555 [git_deploy.py:log_repo_info()] - Git Repo timelapse Detected:
Owner: mainsail-crew
Repository Name: moonraker-timelapse
Path: /home/klipper/moonraker-timelapse
Remote: origin
Branch: main
Remote URL: https://github.com/mainsail-crew/moonraker-timelapse.git
Recovery URL: https://github.com/mainsail-crew/moonraker-timelapse.git
Current Commit SHA: 57bec0dec80e5058eda13cd3586bc2bda0632900
Upstream Commit SHA: 57bec0dec80e5058eda13cd3586bc2bda0632900
Current Version: v0.0.1-142-g57bec0de
Upstream Version: v0.0.1-142-g57bec0de
Rollback Commit: 57bec0dec80e5058eda13cd3586bc2bda0632900
Rollback Branch: main
Rollback Version: v0.0.1-142-g57bec0d
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 0
Diverged: False
2023-08-14 12:46:52,557 [base_deploy.py:log_info()] - Git Repo KlipperScreen: Stored pip version: 21.3.1
2023-08-14 12:46:53,154 [git_deploy.py:log_repo_info()] - Git Repo KlipperScreen Detected:
Owner: jordanruthe
Repository Name: KlipperScreen
Path: /home/klipper/KlipperScreen
Remote: origin
Branch: master
Remote URL: https://github.com/jordanruthe/KlipperScreen.git
Recovery URL: https://github.com/jordanruthe/KlipperScreen.git
Current Commit SHA: 5b5b1f0485342c40c49ba658eecfae99a54a2ac7
Upstream Commit SHA: 0a3dfbeb10565973f4a4235ff08867763c3dab24
Current Version: v0.3.4-6-g5b5b1f04
Upstream Version: v0.3.4-13-g0a3dfbeb
Rollback Commit: 5b5b1f0485342c40c49ba658eecfae99a54a2ac7
Rollback Branch: master
Rollback Version: v0.3.4-6-g5b5b1f0
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 7
Diverged: False
2023-08-14 12:46:53,157 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 4 Days, 22 Hours, 19 Minutes, 37 Seconds
2023-08-14 12:46:53,157 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 4 Days, 22 Hours, 19 Minutes, 39 Seconds
2023-08-14 12:46:53,158 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 4 Days, 22 Hours, 19 Minutes, 42 Seconds
2023-08-14 12:46:53,283 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/klipper/printer_data/comms/moonraker.sock'
2023-08-14 12:46:53,288 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: raspberrypi
2023-08-14 12:46:53,292 [app.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2023-08-14 12:46:53,554 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-08-14 12:46:53,649 [web_deploy.py:_log_client_info()] - Web Client mainsail Detected:
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/klipper/mainsail
Local Version: v2.6.2
Remote Version: v2.7.0
Valid: True
Fallback Client Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.7.0/mainsail.zip
Download Size: 2114605
Content Type: application/zip
Rollback Version: v2.6.2
Rollback Repo: mainsail-crew/mainsail
2023-08-14 12:46:53,849 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2023-08-14 12:46:53,875 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target']
**After=['basic.target', 'network.target', 'sysinit.target', 'system.slice', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=[]
**ExecStart=/home/klipper/klippy-env/bin/python /home/klipper/klipper/klippy/klippy.py /home/klipper/klipper_config/printer.cfg -I /tmp/printer -l /home/klipper/klipper_logs/klippy.log -a /tmp/klippy_uds
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Starts klipper instance  on startup
**User=klipper
2023-08-14 12:46:53,921 [app.py:log_request()] - 101 GET /websocket?token=OPRJJFCIOELGIJSS47GEWM6ZFJSQLVFC (127.0.0.1) [_TRUSTED_USER_] 6.63ms
2023-08-14 12:46:53,922 [websockets.py:open()] - Websocket Opened: ID: 1729570248, Proxied: False, User Agent: , Host Name: 127.0.0.1
2023-08-14 12:46:53,994 [web_deploy.py:_log_client_info()] - Web Client fluidd Detected:
Repo: fluidd-core/fluidd
Channel: stable
Path: /home/klipper/fluidd
Local Version: v1.24.2
Remote Version: v1.25.1
Valid: True
Fallback Client Detected: False
Pre-release: False
Download Url: https://github.com/fluidd-core/fluidd/releases/download/v1.25.1/fluidd.zip
Download Size: 3536974
Content Type: application/zip
Rollback Version: v1.24.2
Rollback Repo: fluidd-core/fluidd
2023-08-14 12:46:53,995 [base_deploy.py:log_info()] - Git Repo timelapse: Next refresh in: 4 Days, 22 Hours, 19 Minutes, 42 Seconds
2023-08-14 12:46:53,995 [base_deploy.py:log_info()] - Git Repo KlipperScreen: Next refresh in: 4 Days, 22 Hours, 19 Minutes, 44 Seconds
2023-08-14 12:46:54,141 [server.py:add_log_rollover_item()] - Klipper Version: v0.11.0-257-ged66982b
2023-08-14 12:46:54,205 [app.py:log_request()] - 404 GET /printer/info (127.0.0.1) [No User] 25.45ms
2023-08-14 12:46:54,210 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/info
2023-08-14 12:46:54,212 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.info
2023-08-14 12:46:54,213 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/query_endstops/status
2023-08-14 12:46:54,218 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.query_endstops.status
2023-08-14 12:46:54,219 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/emergency_stop
2023-08-14 12:46:54,222 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.emergency_stop
2023-08-14 12:46:54,223 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/pause
2023-08-14 12:46:54,226 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.pause
2023-08-14 12:46:54,227 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/query
2023-08-14 12:46:54,235 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.query
2023-08-14 12:46:54,235 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/list
2023-08-14 12:46:54,238 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.list
2023-08-14 12:46:54,238 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/motion_report/dump_stepper
2023-08-14 12:46:54,252 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.motion_report.dump_stepper
2023-08-14 12:46:54,253 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/firmware_restart
2023-08-14 12:46:54,255 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.firmware_restart
2023-08-14 12:46:54,256 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/subscribe
2023-08-14 12:46:54,261 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.subscribe
2023-08-14 12:46:54,262 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/script
2023-08-14 12:46:54,284 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.script
2023-08-14 12:46:54,285 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/help
2023-08-14 12:46:54,292 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.help
2023-08-14 12:46:54,293 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/resume
2023-08-14 12:46:54,296 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.resume
2023-08-14 12:46:54,297 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/motion_report/dump_trapq
2023-08-14 12:46:54,301 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.motion_report.dump_trapq
2023-08-14 12:46:54,301 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/cancel
2023-08-14 12:46:54,303 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.cancel
2023-08-14 12:46:54,303 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/restart
2023-08-14 12:46:54,306 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.restart
2023-08-14 12:46:54,320 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-08-14 12:46:54,328 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-08-14 12:46:54,568 [job_state.py:_handle_started()] - Job state initialized: standby
2023-08-14 12:46:54,879 [klippy_connection.py:_check_ready()] - Klippy ready
2023-08-14 12:46:55,319 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-08-14 12:46:58,412 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2023-08-14 12:48:26,271 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.178.206
2023-08-14 12:48:50,883 [app.py:log_request()] - 101 GET /websocket (192.168.178.206) [_TRUSTED_USER_] 7.91ms
2023-08-14 12:48:50,884 [websockets.py:open()] - Websocket Opened: ID: 1719582312, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36, Host Name: 192.168.178.200
2023-08-14 12:48:50,888 [websockets.py:_handle_identify()] - Websocket 1719582312 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 12:55:06,747 [app.py:prepare()] - Upload Request Received from 192.168.178.206
2023-08-14 12:55:08,012 [app.py:post()] - Processing Uploaded File: HackRFCaseDown.gcode
2023-08-14 12:55:09,517 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-08-14 12:55:09,771 [shell_command.py:_check_proc_success()] - Command (/home/klipper/moonraker-env/bin/python /home/klipper/moonraker/moonraker/components/file_manager/metadata.py -p /home/klipper/gcode_files -f "HackRFCaseDown.gcode") successfully finished
2023-08-14 12:55:09,785 [app.py:log_request()] - 201 POST /server/files/upload (192.168.178.206) [_TRUSTED_USER_] 3044.56ms
2023-08-14 12:55:17,194 [job_state.py:_status_update()] - Job Started: HackRFCaseDown.gcode
2023-08-14 13:21:45,833 [websockets.py:on_close()] - Websocket Closed: ID: 1719582312 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 4.94
2023-08-14 13:48:18,678 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.178.118
2023-08-14 13:48:18,681 [app.py:log_request()] - 101 GET /websocket (192.168.178.118) [_TRUSTED_USER_] 4.63ms
2023-08-14 13:48:18,681 [websockets.py:open()] - Websocket Opened: ID: 1719166000, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36, Host Name: 192.168.178.200
2023-08-14 13:48:18,694 [websockets.py:_handle_identify()] - Websocket 1719166000 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 13:51:48,043 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2023-08-14 13:54:28,832 [websockets.py:write_to_socket()] - Websocket closed while writing: 1719166000
2023-08-14 13:54:33,686 [websockets.py:on_close()] - Websocket Closed: ID: 1719166000 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.99
2023-08-14 13:56:48,045 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.178.206
2023-08-14 14:22:35,204 [app.py:log_request()] - 101 GET /websocket (192.168.178.118) [_TRUSTED_USER_] 5.10ms
2023-08-14 14:22:35,205 [websockets.py:open()] - Websocket Opened: ID: 1719614768, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36, Host Name: 192.168.178.200
2023-08-14 14:22:35,216 [websockets.py:_handle_identify()] - Websocket 1719614768 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 14:28:19,825 [websockets.py:on_close()] - Websocket Closed: ID: 1719614768 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 24.58
2023-08-14 15:01:07,141 [app.py:log_request()] - 101 GET /websocket (192.168.178.118) [_TRUSTED_USER_] 7.53ms
2023-08-14 15:01:07,142 [websockets.py:open()] - Websocket Opened: ID: 1708934048, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36, Host Name: 192.168.178.200
2023-08-14 15:01:07,173 [websockets.py:_handle_identify()] - Websocket 1708934048 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 15:07:07,258 [websockets.py:write_to_socket()] - Websocket closed while writing: 1708934048
2023-08-14 15:07:12,146 [websockets.py:on_close()] - Websocket Closed: ID: 1708934048 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.95
2023-08-14 16:01:48,077 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.178.118
2023-08-14 16:13:14,978 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.178.118
2023-08-14 16:13:14,982 [app.py:log_request()] - 101 GET /websocket (192.168.178.118) [_TRUSTED_USER_] 6.80ms
2023-08-14 16:13:14,983 [websockets.py:open()] - Websocket Opened: ID: 1719614048, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36, Host Name: 192.168.178.200
2023-08-14 16:13:15,005 [websockets.py:_handle_identify()] - Websocket 1719614048 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 16:18:22,041 [websockets.py:on_close()] - Websocket Closed: ID: 1719614048 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 7.04
2023-08-14 16:20:00,710 [timelapse.py:render()] - no frames to render, skip
2023-08-14 16:56:04,341 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.178.206
2023-08-14 16:56:04,345 [app.py:log_request()] - 101 GET /websocket (192.168.178.206) [_TRUSTED_USER_] 7.52ms
2023-08-14 16:56:04,346 [websockets.py:open()] - Websocket Opened: ID: 1719166912, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36, Host Name: 192.168.178.200
2023-08-14 16:56:04,356 [websockets.py:_handle_identify()] - Websocket 1719166912 Client Identified - Name: mainsail, Version: 2.6.2, Type: web
2023-08-14 17:02:48,180 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2023-08-14 17:02:48,198 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1692025338.843081, Usage: 5.35%, Memory: 28768 kB
System Time: 1692025339.850231, Usage: 3.84%, Memory: 28768 kB
System Time: 1692025340.853128, Usage: 4.42%, Memory: 28768 kB
System Time: 1692025341.856968, Usage: 4.42%, Memory: 28768 kB
System Time: 1692025342.860394, Usage: 8.07%, Memory: 28768 kB
System Time: 1692025343.863009, Usage: 5.61%, Memory: 28768 kB
System Time: 1692025344.866696, Usage: 6.25%, Memory: 28768 kB
System Time: 1692025345.868320, Usage: 5.35%, Memory: 28768 kB
System Time: 1692025346.871361, Usage: 4.01%, Memory: 28768 kB
System Time: 1692025347.873404, Usage: 4.15%, Memory: 28768 kB
System Time: 1692025348.879073, Usage: 3.96%, Memory: 28768 kB
System Time: 1692025349.880152, Usage: 4.03%, Memory: 28768 kB
System Time: 1692025350.884904, Usage: 5.13%, Memory: 28768 kB
System Time: 1692025351.890067, Usage: 5.24%, Memory: 28768 kB
System Time: 1692025352.893991, Usage: 8.67%, Memory: 28768 kB
System Time: 1692025353.898475, Usage: 4.17%, Memory: 28768 kB
System Time: 1692025354.898487, Usage: 4.86%, Memory: 28768 kB
System Time: 1692025355.903850, Usage: 4.07%, Memory: 28768 kB
System Time: 1692025356.905112, Usage: 4.08%, Memory: 28768 kB
System Time: 1692025357.906124, Usage: 4.9%, Memory: 28768 kB
System Time: 1692025358.909834, Usage: 4.77%, Memory: 28768 kB
System Time: 1692025359.915372, Usage: 4.82%, Memory: 28768 kB
System Time: 1692025360.918784, Usage: 4.03%, Memory: 28768 kB
System Time: 1692025361.922884, Usage: 3.84%, Memory: 28768 kB
System Time: 1692025362.928275, Usage: 7.97%, Memory: 28768 kB
System Time: 1692025363.934067, Usage: 5.1%, Memory: 28768 kB
System Time: 1692025364.933590, Usage: 4.7%, Memory: 28768 kB
System Time: 1692025365.937931, Usage: 3.9%, Memory: 28768 kB
System Time: 1692025366.941642, Usage: 3.75%, Memory: 28768 kB
System Time: 1692025367.945471, Usage: 3.71%, Memory: 28768 kB
CPU Temperature: 57.996
2023-08-14 17:02:48,229 [proc_stats.py:_handle_shutdown()] - Throttled Flags: Previously Under-Volted Previously Throttled
2023-08-14 17:16:48,096 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.178.118
2023-08-14 17:20:37,512 [app.py:prepare()] - Upload Request Received from 192.168.178.206
2023-08-14 17:20:37,521 [app.py:post()] - Processing Uploaded File: moonraker.conf
2023-08-14 17:20:37,537 [app.py:log_request()] - 201 POST /server/files/upload (192.168.178.206) [_TRUSTED_USER_] 28.88ms
2023-08-14 17:20:37,653 [websockets.py:on_close()] - Websocket Closed: ID: 1729570248 Close Code: 1000, Close Reason: None, Pong Time Elapsed: 3.73
2023-08-14 17:20:37,660 [websockets.py:on_close()] - Websocket Closed: ID: 1719166912 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 3.31
2023-08-14 17:20:37,665 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-08-14 17:20:37,696 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 18
overflow_pages: 0
entries: 69
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 32
overflow_pages: 0
entries: 117
mainsail:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
mobileraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 4
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
timelapse:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
update_manager:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 2
overflow_pages: 1
entries: 7
webcams:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 2
```

**Comment by Barsonax** [comment]
Seems to happen with other special characters like ^ and $ as well

**Comment by Arksine** [comment]
Hi.  I have investigated this and believe that I have corrected the issue in commit e66744b6e9b3475cb2fb3908777112992a01bf76.  That said, I do not have a Shelly device, so I cannot test it.

**Comment by Barsonax** [comment]
Will it help if I test it and if so how or will you just release it?

**Comment by Arksine** [comment]
I pushed the commit as I don't think it will cause a regression.  You can update Moonraker and test to see if it resolves your issue.

**Comment by Barsonax** [comment]
I updated to v0.9.2-5-ge66744b6 and this fixes the problem for me

**Comment by MoJo2600** [comment]
I can confirm it is working now with moonraker `v0.9.2-6-gf735c041`
