### ISSUE TITLE
Changing a cfg file - Unable to save File 

### ISSUE THREAD

**Issue by mikepiko** [Arksine/moonraker#708]
### What happened

I created a new cfg File, added some parameters afterwards and cannot save the File.

I get an Error "Cannot Upload File" 

### Client

Mainsail

### Browser

Chrome

### How to reproduce

Create a File, open it and just write a line and hit save and exit

### Additional information

In the Logfile it will return some checksum mismatch:

`2023-08-27 11:11:18,844 [app.py:prepare()] - Upload Request Received from 192.168.100.2
2023-08-27 11:11:18,856 [app.py:post()] - Processing Uploaded File: bedfans.cfg
2023-08-27 11:11:18,875 [app.py:log_request()] - 201 POST /server/files/upload (192.168.100.2) [_TRUSTED_USER_] 34.41ms
2023-08-27 11:11:37,235 [app.py:prepare()] - Upload Request Received from 192.168.100.2
2023-08-27 11:11:37,245 [web.py:log_exception()] - Uncaught exception POST /server/files/upload (192.168.100.2)
HTTPServerRequest(protocol='http', host='voron24.starfleetcommand.de', method='POST', uri='/server/files/upload', version='HTTP/1.1', remote_ip='192.168.100.2')
Traceback (most recent call last):
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/pi/moonraker/moonraker/app.py", line 923, in post
    raise self.server.error(
moonraker.utils.ServerError: File checksum mismatch: expected 9dd4e1e29eb43a46fb49134f80a63d852e819d699373504e825707cbc2e2ff16, calculated c7218f767097e6452b4e88dc3d6288adfb933f5142b401308697d03c4a1050b0
`

After doing some more Investigation i found out that the Problem is happening when you won´t have Blank Line at the End of the File.

**Comment by Arksine** [comment]
This doesn't appear to be a bug in Moonraker, the client is calculating the checksum incorrectly.
