### ISSUE TITLE
server restart with exit code (help!!!!)

### ISSUE THREAD

**Issue by thiesymon** [Arksine/moonraker#745]
### What happened

after installed moonraker it shows 
`-------------------- Log Start | Tue Nov 14 21:10:27 2023 --------------------
data_path: /home/thiesy/printer_data
is_default_data_path: False
config_file: /home/thiesy/printer_data/config/moonraker.conf
startup_warnings: []
verbose: True
debug: True
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 05546b52f52749cd82ba589d6ebf6c76
unix_socket_path: /home/thiesy/printer_data/comms/moonraker.sock
software_version: v0.8.0-197-g975011d
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/thiesy/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
msgspec_enabled: False
uvloop_enabled: False
2023-11-15 05:10:27,790 [server.py:main()] - Server Config Error
Traceback (most recent call last):
  File "/home/thiesy/moonraker/moonraker/server.py", line 598, in main
    server = Server(app_args, log_manager, event_loop)
  File "/home/thiesy/moonraker/moonraker/server.py", line 77, in __init__
    self.config = config = self._parse_config()
  File "/home/thiesy/moonraker/moonraker/server.py", line 141, in _parse_config
    config = confighelper.get_configuration(self, self.app_args)
  File "/home/thiesy/moonraker/moonraker/confighelper.py", line 1051, in get_configuration
    source.read_file(start_path)
  File "/home/thiesy/moonraker/moonraker/confighelper.py", line 1039, in read_file
    self._parse_file(main_conf, [])
  File "/home/thiesy/moonraker/moonraker/confighelper.py", line 983, in _parse_file
    raise ConfigError(
moonraker.confighelper.ConfigError: No files matching include directive [include octoeverywhere-system.cfg]`

### Client

Fluidd

### Browser

Microsoft Edge

### How to reproduce

1. python 3.10

1. kiauh.sh

**Comment by Arksine** [comment]
As no one has been able to provide further feedback I'm going to close this.  If you are still having issues I recommend asking for assistance on the Klipper Discourse.
