### ISSUE TITLE
Spoolman announcement thread not registering

### ISSUE THREAD

**Issue by gschmidl** [Arksine/moonraker#762]
### What happened

Installed the docker image for spoolman from ghcr.io/donkie/spoolman:latest

Added this configuration to moonraker.conf:

```
[spoolman]
server: http://192.168.1.178:7912
sync_rate: 5
```

Leads to this error:

```
2023-12-05 20:59:29,881 [server.py:load_component()] - Unable to load component: (spoolman)
Traceback (most recent call last):
  File "/usr/data/moonraker/moonraker/moonraker/server.py", line 274, in load_component
    component = load_func(config)
  File "/usr/data/moonraker/moonraker/moonraker/components/spoolman.py", line 203, in load_component
    return SpoolManager(config)
  File "/usr/data/moonraker/moonraker/moonraker/components/spoolman.py", line 48, in __init__
    announcements.register_feed("spoolman")
AttributeError: 'Announcements' object has no attribute 'register_feed'
```

Web access to spoolman at the configured URL works.

### Client

Mainsail, Fluidd

### Browser

Microsoft Edge

### How to reproduce

Add configuration pointing at a Spoolman docker container.

### Additional information

I tried to cut it down to the important bit.

[moonraker.log](https://github.com/Arksine/moonraker/files/13572737/moonraker.log)

**Comment by laufantn** [comment]
i have the same problem, i have tried several times but nothing has helped. i use klipper / fluidd on the creality sonic pad.
