### ISSUE TITLE
AttributeError: module 'moonraker.components.job_queue' has no attribute 'load_component'

### ISSUE THREAD

**Issue by ChaosBlades** [Arksine/moonraker#886]
### What happened

Updated my printer and getting following from Moonraker
```
 moonraker.service - API Server for Klipper SV1
     Loaded: loaded (/etc/systemd/system/moonraker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-07-14 08:34:54 EDT; 6s ago
    Process: 2965 ExecStart=/home/pi/moonraker-env/bin/python $MOONRAKER_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2965 (code=exited, status=1/FAILURE)
        CPU: 1.563s
```
Ran` /home/pi/moonraker-env/bin/python -m pip install --force-reinstall `
Then get...
```
moonraker.service - API Server for Klipper SV1
     Loaded: loaded (/etc/systemd/system/moonraker.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-07-14 08:35:05 EDT; 1s ago
   Main PID: 3019 (python)
      Tasks: 1 (limit: 4026)
        CPU: 1.298s
     CGroup: /system.slice/moonraker.service
             └─3019 /home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/moonraker.py -d /home/pi/printer_data -c /home/pi/klipper_config/moonraker.conf -l /home/pi/klipper_logs/moonraker.log

Jul 14 08:35:06 fluiddpi python[3019]: [server.py:main()] - Moonraker Error
Jul 14 08:35:06 fluiddpi python[3019]: Traceback (most recent call last):
Jul 14 08:35:06 fluiddpi python[3019]:   File "/home/pi/moonraker/moonraker/server.py", line 662, in main
Jul 14 08:35:06 fluiddpi python[3019]:     server.load_components()
Jul 14 08:35:06 fluiddpi python[3019]:   File "/home/pi/moonraker/moonraker/server.py", line 261, in load_components
Jul 14 08:35:06 fluiddpi python[3019]:     self.load_component(config, component)
Jul 14 08:35:06 fluiddpi python[3019]:   File "/home/pi/moonraker/moonraker/server.py", line 296, in load_component
Jul 14 08:35:06 fluiddpi python[3019]:     load_func = getattr(module, "load_component")
Jul 14 08:35:06 fluiddpi python[3019]: AttributeError: module 'moonraker.components.job_queue' has no attribute 'load_component'
Jul 14 08:35:06 fluiddpi python[3019]: [server.py:main()] - Server Shutdown
```
Ran `./scripts/install-moonraker.sh ` after that.
Now I get the same as the first error.

### Client

Fluidd

### Browser

Firefox

### How to reproduce

Just ran a full update through KlipperScreen.

**Comment by ChaosBlades** [comment]
Did a complete OS re-install. Seems this had something to do with my moonraker.conf file even though I have not changed it in a very long time as this issue re-appeared after I added my old config back. Needed to re-make it from scratch. Did not identify the specific problem with the file.
