### ISSUE TITLE
Can't edit pritner.cfg directly from mainsail

### ISSUE THREAD

**Issue by MarcBresson** [Arksine/moonraker#929]
### What happened

I tried editing and saving the printer.cfg file directly from mainsail's interface, but I got the following error in the network tab of my browser (with a status code 500).

```
Traceback (most recent call last):
 File "/home/mks/moonraker-env/lib/python3.7/shutil.py", line 563, in move
 os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/moonraker.upload-2179.mru' -> '/home/mks/klipper_config/printer.cfg'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/mks/moonraker/moonraker/components/file_manager/file_manager.py", line 964, in _process_uploaded_file
 uploa…, 500)
moonraker.utils.exceptions.ServerError: Unable to save file

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/mks/moonraker-env/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
 result = await result
 File "/home/mks/moonraker/moonraker/components/application.py", line 1018, in post
 e.status_code, str(e))
tornado.web.HTTPError: HTTP 500: Internal Server Error (Unable to save file)
```

Editing any other file works, and editing printer.cfg with ssh works too.

### Client

Mainsail

### Browser

Firefox

### How to reproduce

Moonraker version: v0.9.3-4-ga4604e3 (but strangely enough, mainsail reports different version number depending on where you look, cf. screenshot)
![image](https://github.com/user-attachments/assets/31056fad-b54c-465d-9105-1e0b0c483531)

Mainsail version: 2.13.1

### Additional information

[moonraker.log](https://github.com/user-attachments/files/18233611/moonraker.log)

**Comment by MarcBresson** [comment]
nevermind, after looking at the log file, I saw the permission error. For some reason, `printer.cfg` (and only it) was owned by root.
